import { Toaster } from 'react-hot-toast'
import { StateContext } from '../../context/StateContext'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <StateContext>
        <Toaster position="top-center"/>
        {children}
      </StateContext>
      </body>
    </html>
  )
}
